spring.application.name=AccessControl


spring.datasource.url=jdbc:postgresql://localhost:5432/access_control
spring.datasource.username=postgres
spring.datasource.password=xxUPDATEPASSWORDxx

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080